# Generated by Django 3.1.7 on 2021-06-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_cropdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('crop_req', models.CharField(max_length=255)),
                ('quantity_req', models.IntegerField()),
            ],
        ),
    ]
