# Generated by Django 3.1.7 on 2021-06-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_advertisementdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('complaint_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
