# Generated by Django 3.1.7 on 2021-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_complaintdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmersRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('fphone', models.CharField(max_length=255)),
                ('fadd', models.CharField(max_length=255)),
                ('cname', models.CharField(max_length=255)),
                ('cphone', models.CharField(max_length=255)),
                ('cadd', models.CharField(max_length=255)),
                ('crop_req', models.CharField(max_length=255)),
                ('quantity_req', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
